using System;
using System.Collections.Generic;
using System.IO;
using WixToolset.Dtf.WindowsInstaller;

namespace MsiInspector.Tests
{
    /// <summary>
    /// Builds tiny MSI databases on disk for unit tests. Uses DTF directly
    /// (not via MsiInspector's shim) so the test fixtures themselves do not
    /// depend on the SUT's read path.
    /// </summary>
    internal static class TestMsiBuilder
    {
        /// <summary>
        /// Creates a minimal MSI with Directory, Component, and File tables
        /// populated for the given fixture spec. Returns the path to the MSI.
        /// </summary>
        public static string CreateMinimal(string fixtureName, IReadOnlyList<DirectoryEntry> directories, IReadOnlyList<ComponentEntry> components, IReadOnlyList<FileEntry> files)
        {
            var dir = Path.Combine(Path.GetTempPath(), "MsiInspectorTests", fixtureName);
            Directory.CreateDirectory(dir);
            var msiPath = Path.Combine(dir, fixtureName + ".msi");
            if (File.Exists(msiPath)) File.Delete(msiPath);

            using var db = new Database(msiPath, DatabaseOpenMode.CreateDirect);

            // Set ProductName/ProductVersion etc via summary info.
            using (var summary = db.SummaryInfo)
            {
                summary.Title = "MsiInspector Test Fixture";
                summary.Subject = fixtureName;
                summary.Author = "MsiInspector.Tests";
                summary.Keywords = "test";
                summary.Comments = "Generated by TestMsiBuilder";
                summary.Template = "x64;1033";
                summary.PageCount = 200;
                summary.WordCount = 0;
                summary.RevisionNumber = Guid.NewGuid().ToString("B");
                summary.CreatingApp = "MsiInspector.Tests";
                summary.Persist();
            }

            CreateDirectoryTable(db);
            CreateComponentTable(db);
            CreateFileTable(db);

            foreach (var d in directories)
            {
                ExecuteNonQuery(db,
                    "INSERT INTO `Directory` (`Directory`, `Directory_Parent`, `DefaultDir`) VALUES (?, ?, ?)",
                    d.Directory, d.ParentDirectory, d.DefaultDir);
            }
            foreach (var c in components)
            {
                ExecuteNonQuery(db,
                    "INSERT INTO `Component` (`Component`, `ComponentId`, `Directory_`, `Attributes`, `Condition`, `KeyPath`) VALUES (?, ?, ?, ?, ?, ?)",
                    c.Component, c.ComponentId, c.Directory, c.Attributes, c.Condition, c.KeyPath);
            }
            foreach (var f in files)
            {
                ExecuteNonQuery(db,
                    "INSERT INTO `File` (`File`, `Component_`, `FileName`, `FileSize`, `Version`, `Language`, `Attributes`, `Sequence`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    f.File, f.Component, f.FileName, f.FileSize, f.Version, f.Language, f.Attributes, f.Sequence);
            }

            db.Commit();
            return msiPath;
        }

        private static void CreateDirectoryTable(Database db)
        {
            ExecuteNonQuery(db,
                "CREATE TABLE `Directory` (" +
                "`Directory` CHAR(72) NOT NULL, " +
                "`Directory_Parent` CHAR(72), " +
                "`DefaultDir` CHAR(255) NOT NULL LOCALIZABLE " +
                "PRIMARY KEY `Directory`)");
        }

        private static void CreateComponentTable(Database db)
        {
            ExecuteNonQuery(db,
                "CREATE TABLE `Component` (" +
                "`Component` CHAR(72) NOT NULL, " +
                "`ComponentId` CHAR(38), " +
                "`Directory_` CHAR(72) NOT NULL, " +
                "`Attributes` SHORT NOT NULL, " +
                "`Condition` CHAR(255), " +
                "`KeyPath` CHAR(72) " +
                "PRIMARY KEY `Component`)");
        }

        private static void CreateFileTable(Database db)
        {
            ExecuteNonQuery(db,
                "CREATE TABLE `File` (" +
                "`File` CHAR(72) NOT NULL, " +
                "`Component_` CHAR(72) NOT NULL, " +
                "`FileName` CHAR(255) NOT NULL LOCALIZABLE, " +
                "`FileSize` LONG NOT NULL, " +
                "`Version` CHAR(72), " +
                "`Language` CHAR(20), " +
                "`Attributes` SHORT, " +
                "`Sequence` LONG NOT NULL " +
                "PRIMARY KEY `File`)");
        }

        private static void ExecuteNonQuery(Database db, string sql, params object?[] parameters)
        {
            using var view = db.OpenView(sql);
            if (parameters.Length > 0)
            {
                using var record = new Record(parameters.Length);
                for (var i = 0; i < parameters.Length; i++)
                {
                    var p = parameters[i];
                    if (p == null) continue;
                    if (p is int i32) record.SetInteger(i + 1, i32);
                    else if (p is long i64) record.SetInteger(i + 1, (int)i64);
                    else record.SetString(i + 1, p.ToString());
                }
                view.Execute(record);
            }
            else
            {
                view.Execute();
            }
        }

        public sealed class DirectoryEntry
        {
            public string Directory { get; set; } = string.Empty;
            public string? ParentDirectory { get; set; }
            public string DefaultDir { get; set; } = ".";
        }

        public sealed class ComponentEntry
        {
            public string Component { get; set; } = string.Empty;
            public string ComponentId { get; set; } = "{00000000-0000-0000-0000-000000000000}";
            public string Directory { get; set; } = string.Empty;
            public int Attributes { get; set; }
            public string? Condition { get; set; }
            public string? KeyPath { get; set; }
        }

        public sealed class FileEntry
        {
            public string File { get; set; } = string.Empty;
            public string Component { get; set; } = string.Empty;
            public string FileName { get; set; } = string.Empty;
            public int FileSize { get; set; } = 1024;
            public string? Version { get; set; }
            public string? Language { get; set; }
            public int Attributes { get; set; }
            public int Sequence { get; set; } = 1;
        }
    }
}
